name: CI

on:
  push:
    branches:
      - dev

jobs:
  release-automation:
    name: Build App
    strategy:
      matrix:
        ui_type: [QWidget]
        platform: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.platform == 'ubuntu-latest' && 'archlinux:base-devel' || '' }}
    permissions:
      contents: write

    steps:
      - name: Linux - Inspect memory
        if: matrix.platform == 'ubuntu-latest'
        run: free -h

      - name: Linux - Hack makepkg
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sed -i '/E_ROOT/d' /usr/bin/makepkg

      - name: Linux - update database
        if: matrix.platform == 'ubuntu-latest'
        run: |
          pacman --noconfirm --noprogressbar -Sy
          pacman --noconfirm -S git grep
          git --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Tag Repo
        run: |
          git config --global --add safe.directory '*'
          git tag -d Prerelease
          git tag Prerelease

      - name: Linux - build
        if: matrix.platform == 'ubuntu-latest'
        run: |
          cd ../
          mv Qv2ray/PKGBUILD .
          makepkg --noconfirm -sf
          ls -alh
          cd Qv2ray
          cp ../qv2ray-dev-git-* .
          echo "pkgver=$(grep --only-matching -P '(?<=pkgver=).*' ../PKGBUILD)" >> $GITHUB_ENV
          echo "pkgrel=$(grep --only-matching -P '(?<=pkgrel=).*' ../PKGBUILD)" >> $GITHUB_ENV

      - uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: Prerelease
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

      - name: Upload packages
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Prerelease
          files: qv2ray-dev-git-${{ env.pkgver }}-${{ env.pkgrel }}-x86_64.pkg.tar.zst
          prerelease: true
